"""create column data

Revision ID: 397307520b97
Revises: 9e659dcbfbda
Create Date: 2024-07-06 14:39:34.908669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '397307520b97'
down_revision = '9e659dcbfbda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
