"""Edit is_in_stock attribute

Revision ID: 3b6b68a89878
Revises: f7eb069a1171
Create Date: 2024-07-05 11:12:35.749998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b6b68a89878'
down_revision = 'f7eb069a1171'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('is_in_stock',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('is_in_stock',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###
