"""Add Address table

Revision ID: 7a8b273604e8
Revises: 
Create Date: 2024-07-10 23:27:59.182705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a8b273604e8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('apartment', sa.String(length=120), nullable=False))
        batch_op.drop_column('zip_code')
        batch_op.drop_column('state')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('state', sa.VARCHAR(length=120), nullable=False))
        batch_op.add_column(sa.Column('zip_code', sa.VARCHAR(length=10), nullable=False))
        batch_op.drop_column('apartment')
        batch_op.drop_column('phone_number')

    # ### end Alembic commands ###
