"""add category attribute

Revision ID: 8f98585dab64
Revises: 3b6b68a89878
Create Date: 2024-07-05 13:22:57.480413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f98585dab64'
down_revision = '3b6b68a89878'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=120), nullable=True))
        batch_op.drop_column('is_in_stock')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_in_stock', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('category')

    # ### end Alembic commands ###
