"""Add price column to the order

Revision ID: 9e659dcbfbda
Revises: a6a93661a491
Create Date: 2024-07-06 13:33:39.960648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e659dcbfbda'
down_revision = 'a6a93661a491'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order') as batch_op:
        batch_op.add_column(sa.Column('price', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order') as batch_op:
        batch_op.drop_column('price')

    # ### end Alembic commands ###
